// <auto-generated />
namespace DatabaseFirstRepeat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Customer_RemoveColumn_TelNo_TakeBackup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Customer_RemoveColumn_TelNo_TakeBackup));
        
        string IMigrationMetadata.Id
        {
            get { return "202112282348378_Customer_RemoveColumn_TelNo_TakeBackup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
